databases:
  - name: myapp-postgres
    databaseName: volunteer_tree_i4uf
    user: m_nagasaka
    region: Oregon


services:
  - type: web
    name: volunteer_tree_i4uf
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "build exec puma -C config/puma.rb"
    preDeployCommand: ./bin/rails db:migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: volunteer_tree_i4uf
          property: connectionString
      - key: TAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
